version: '3.8'

services:
  postgres:
    image: postgres:13.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=vitalii_notes
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
